/** Declaration file generated by dts-gen */

export function fieldFormatter(map: any, data: any): any;

export function rowFormatter(maps: any, data: any, options: any): any;

export namespace getAsyncFlatFileCreator {
    function getAsyncFlatFileCreator(maps: any, options: any): void;

}

